<?php
/**
 * @file
 * Módulo para gestionar los templates bases del sitio
 */

function BRM_maggi_links__system_main_menu($variables) {
  var_dump($variables);
  $html = "<div>\n";
  $html .= "  <ul>\n";  
  foreach ($variables['links'] as $link) {
    $html .= "<li>".l($link['title'], $link['path'], $link)."</li>";
  }
  $html .= "  </ul>\n";
  $html .= "</div>\n";

  return $html;
}

/*Poner clase en los menús*/
function BRM_maggi_menu_link(array $variables) {
  var_dump($variables);
  // Add class for li.
  $variables['element']['#attributes']['class'][] = 'menu-' . $variables['element']['#original_link']['mlid'];
  // Add class for a.
  $variables['element']['#localized_options']['attributes']['class'][] = 'menu-' . $variables['element']['#original_link']['mlid'];
  return theme_menu_link($variables);
}


function BRM_maggi_block_info() {
    $blocks = array();
      $blocks['header'] = array(
         'info' => t("tema base del header del sitio"),
         'cache' => DRUPAL_CACHE_CUSTOM,
      );
      $blocks['footer'] = array(
         'info' => t("tema base del footer del sitio"),
         'cache' => DRUPAL_CACHE_CUSTOM,
      );
      $blocks['block_label_recetario'] = array(
         'info' => t("block static - Recetario"),
         'cache' => DRUPAL_CACHE_CUSTOM,
      );
      $blocks['block_label_productos'] = array(
         'info' => t("block static - Productos"),
         'cache' => DRUPAL_CACHE_CUSTOM,
      );
      $blocks['slider_recetario'] = array(
         'info' => t("Slider: Recetario"),
         'cache' => DRUPAL_CACHE_CUSTOM,
      );
    return $blocks;
}


/**
 * Implementa hook_block_view().
 */
function BRM_maggi_block_view($delta = '') {
	$variables= array();
  switch ($delta) {

    case 'header':
      $block['content'] = theme('header',$variables);
      return $block;
    break;  

    case 'footer':
      $block['content'] = theme('footer',$variables);
      return $block;
    break;
    case 'block_label_recetario':
      $block['content'] = theme('block_label_recetario',$variables);
      return $block;
    break;
    case 'block_label_productos':
      $block['content'] = theme('block_label_productos',$variables);
      return $block;
    break; 
    case 'slider_recetario':
      $variables['nox'] = get_nodes_nodequeue(1);
      $block['content'] = theme('slider_recetario',$variables);
      return $block;
    break;
    case 'recetas_producto_recomendadas':
      $variables['nox'] = get_nodes_nodequeue(1);
      $block['content'] = theme('slider_recetario',$variables);
      return $block;
    break; 
  }
}

/*Llamdo de los templates base*/
function BRM_maggi_theme() {
   return array(
    'header' => array(
        'template' => 'theme/header'
      ),
     	'footer' => array(
       	'template' => 'theme/footer'
     	),
      'block_label_recetario' => array(
        'template' => 'theme/block_label_recetario'
      ),
      'block_label_productos' => array(
        'template' => 'theme/block_label_productos'
      ),
      'slider_recetario' => array(
        'template' => 'theme/slider_recetario'
      ),
     );
}

//Funcion que permite reemplazar caracteres especiales
function limpiarMiga($nombreVariable){
  $limpieza = array(  " " => "_",
            "á" => "a",
            "é" => "e",
            "í" => "i",
            "ó" => "o",
            "ú" => "u",
            "Á" => "A",
            "É" => "E",
            "Í" => "I",
            "Ó" => "O",
            "Ú" => "U",
            "ñ" => "n",
            "Ñ" => "Ñ",           
            "&aacute;" => "a",
            "&eacute;" => "e",
            "&iacute;" => "i",
            "&oacute;" => "o",
            "&uacute;" => "u",
            "&Aacute;" => "A",
            "&Eacute;" => "E",
            "&Iacute;" => "I",
            "&Oacute;" => "O",
            "&Uacute;" => "U",
            "&ntilde;" => "n",
            "&Ntilde;" => "Ñ",
            "(" => "_",
            ")" => "_"
  );
  $nombreVariable = strtr($nombreVariable, $limpieza);
  return $nombreVariable;
}

function get_nodes_nodequeue($idNodeque){

  $result = db_query("select * FROM mgg_nodequeue_nodes WHERE qid = :fx ORDER BY position ASC;",
            array(':fx' => $idNodeque));
  while ($record = $result->fetchAssoc()){
    $arraynodos[] = $record;
  };

  foreach ($arraynodos as $key => $value) {
    $nodoso = node_load($value["nid"]);
    $nodos[] = $nodoso;
  }
  //$nodos['tax'] = $arraynodos[0];
  return $nodos;

}