<?php
/**
 * @file
 * Módulo de revisión para palabras prohibidas en las contraseñas
 */


function blaklist_password_block_info() {
    $blocks = array();
    $blocks['blaklist_password'] = array(
       'info' => t("Lista de palabras bloqueadas para la creación de contraseñas"),
       'cache' => DRUPAL_CACHE_CUSTOM,
        );
    return $blocks;
}

// Alter the registration form

function busquedaPalabra(){
	$result = db_select('blacklist_password','palabras')
   		 ->fields('palabras')
    	 ->condition('activa','S','=')
         ->execute();

    	while($record = $result->fetchAssoc()) {
        $palabra[]=$record['palabra'];
   		 }
		return $palabra;
}

function blaklist_password_menu() {
  $items = array();	
  $items['lalistabanea'] = array(
    'title' => 'baneado',
    'page callback' => 'baneado',
	'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function baneado(){
	$blacklist=busquedaPalabra();
	return  drupal_json_output($blacklist);
	
}




/*function blaklist_password_form_alter(&$form, &$form_state, $form_id) {

	$palabra=array();
	
	if($form_id=='user_register_form'){
		
		$blacklist = busquedaPalabra();
		
  		$password = $form['account']['pass'];


  		echo '<pre>';
		print_r($password);
		echo '</pre>';

		foreach($blacklist as $word) {

			$word =  _password_crypt('sha512',$word, _password_generate_salt(DRUPAL_HASH_COUNT));
			print_r($password);
		    if(strcmp($password, $word) == 0) {
		   	print_r($word);
		      form_set_error("account", t("El uso de ésta palabra no está permitido.", array('@word' => $word)));
		      break;
		    }
		    print_r($word);
		  }
		
	}
}*/